# Generated by Django 4.0 on 2021-12-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorted_api', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
