# Generated by Django 4.0.1 on 2022-01-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorted_api', '0003_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
