# Generated by Django 4.0.1 on 2022-01-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorted_api', '0004_alter_item_model_alter_item_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
