# Generated by Django 4.0.1 on 2022-01-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorted_api', '0006_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='gearList',
            field=models.ManyToManyField(blank=True, related_name='kits', to='sorted_api.Item'),
        ),
    ]
